# Generated by Django 5.2.16 on 2026-07-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientPortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("client_code", models.BigIntegerField(unique=True)),
                ("cnpj", models.CharField(blank=True, max_length=20)),
                ("client_name", models.CharField(max_length=150)),
                ("salesperson_name", models.CharField(max_length=150)),
                ("nk_supervisor", models.CharField(max_length=50)),
                ("municipio", models.CharField(blank=True, max_length=60)),
                ("estado", models.CharField(blank=True, max_length=60)),
                ("registered_at", models.DateField(blank=True, null=True)),
                ("last_changed_at", models.DateField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AccumulatedSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nk_supervisor", models.CharField(max_length=50)),
                ("nk_vendedor", models.CharField(max_length=50)),
                ("salesperson_name", models.CharField(max_length=150)),
                ("client_code", models.BigIntegerField()),
                ("cnpj", models.CharField(blank=True, max_length=20)),
                ("client_name", models.CharField(blank=True, max_length=150)),
                ("sale_date", models.DateField()),
                ("subgroup_name", models.CharField(max_length=60)),
                ("total_quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("total_value", models.DecimalField(decimal_places=3, max_digits=18)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["sale_date"], name="sales_histo_sale_da_d9f52c_idx"),
                    models.Index(fields=["nk_vendedor"], name="sales_histo_nk_vend_670b32_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nk_vendedor", "client_code", "subgroup_name", "sale_date"),
                        name="uniq_accumulated_sale_row",
                    )
                ],
            },
        ),
    ]
