# Generated by Django 5.2.16 on 2026-07-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales_history", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accumulatedsale",
            name="uniq_accumulated_sale_row",
        ),
    ]
