# Generated by Django 5.2.16 on 2026-07-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_history", "0002_remove_accumulatedsale_uniq_accumulated_sale_row"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributionBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ano", models.PositiveIntegerField()),
                ("mes", models.PositiveSmallIntegerField()),
                ("salesperson_name", models.CharField(max_length=150)),
                ("subgroup_name", models.CharField(max_length=60)),
                ("total_quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["ano", "mes"], name="sales_histo_ano_6ccc24_idx"),
                    models.Index(fields=["salesperson_name"], name="sales_histo_salespe_821e6a_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ano", "mes", "salesperson_name", "subgroup_name"),
                        name="uniq_distribution_baseline_row",
                    )
                ],
            },
        ),
    ]
