# Generated by Django 5.2.16 on 2026-07-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_history", "0003_distributionbaseline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distributionbaseline",
            name="salesperson_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="distributionbaseline",
            name="total_quantity",
            field=models.DecimalField(decimal_places=0, max_digits=18),
        ),
    ]
