# Generated by Django 5.2.16 on 2026-07-13 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("cycles", "0001_initial"),
        ("hierarchy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "granularity",
                    models.CharField(
                        choices=[("GROUP", "Grupo"), ("SUBGROUP", "Subgrupo"), ("PRODUCT", "Produto")],
                        max_length=10,
                    ),
                ),
                ("quantity_kg", models.PositiveIntegerField()),
                ("distributed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="cycles.cycle",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="catalog.productgroup",
                    ),
                ),
                (
                    "owner_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="hierarchy.hierarchynode",
                    ),
                ),
                (
                    "parent_allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="allocations.goalallocation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="catalog.product",
                    ),
                ),
                (
                    "subgroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="catalog.productsubgroup",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["cycle", "owner_node"], name="allocations_cycle_i_d457f6_idx"),
                    models.Index(fields=["parent_allocation"], name="allocations_parent__689cd4_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("granularity", "GROUP"),
                                ("group__isnull", False),
                                ("product__isnull", True),
                                ("subgroup__isnull", True),
                            ),
                            models.Q(
                                ("granularity", "SUBGROUP"),
                                ("group__isnull", True),
                                ("product__isnull", True),
                                ("subgroup__isnull", False),
                            ),
                            models.Q(
                                ("granularity", "PRODUCT"),
                                ("group__isnull", True),
                                ("product__isnull", False),
                                ("subgroup__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="allocation_granularity_matches_target",
                    )
                ],
            },
        ),
    ]
