# Generated by Django 5.2.16 on 2026-07-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlogentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("CRIACAO", "Criação"),
                    ("ATUALIZACAO", "Atualização"),
                    ("INATIVACAO", "Inativação"),
                    ("REATIVACAO", "Reativação"),
                    ("REABERTURA", "Reabertura"),
                ],
                max_length=20,
            ),
        ),
    ]
