# Generated by Django 5.2.16 on 2026-07-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ano", models.PositiveIntegerField()),
                ("mes", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ABERTO", "Aberto"), ("FECHADO", "Fechado")],
                        default="ABERTO",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("ano", "mes"), name="uniq_cycle_ano_mes"),
                    models.CheckConstraint(
                        condition=models.Q(("mes__gte", 1), ("mes__lte", 12)), name="cycle_mes_valido"
                    ),
                ],
            },
        ),
    ]
