# Generated by Django 5.2.16 on 2026-07-13 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductSubgroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subgroups",
                        to="catalog.productgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "subgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.productsubgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalProductMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_code", models.CharField(max_length=100, unique=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_mappings",
                        to="catalog.productgroup",
                    ),
                ),
                (
                    "subgroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_mappings",
                        to="catalog.productsubgroup",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="productsubgroup",
            constraint=models.UniqueConstraint(fields=("group", "nome"), name="uniq_subgroup_nome_por_group"),
        ),
        migrations.AddConstraint(
            model_name="externalproductmapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("group__isnull", False), ("subgroup__isnull", True)),
                    models.Q(("group__isnull", True), ("subgroup__isnull", False)),
                    _connector="OR",
                ),
                name="external_mapping_targets_exactly_one",
            ),
        ),
    ]
