# Generated by Django 5.2.16 on 2026-07-14 19:44

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("hierarchy", "0002_externalsalespersonmapping"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="hierarchy_node",
        ),
        migrations.AddField(
            model_name="user",
            name="hierarchy_nodes",
            field=models.ManyToManyField(blank=True, related_name="users", to="hierarchy.hierarchynode"),
        ),
    ]
