# Generated by Django 5.2.16 on 2026-07-21 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Já existe um usuário com esse nome."},
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Use o nome completo da pessoa, sem números.", regex="^[^\\d]+$"
                    )
                ],
                verbose_name="nome completo",
            ),
        ),
    ]
