# Generated by Django 5.2.16 on 2026-07-13 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HierarchyNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("GERENTE", "Gerente"),
                            ("REGIONAL", "Coordenador Regional"),
                            ("LOCAL", "Coordenador Local"),
                            ("SUPERVISOR", "Supervisor"),
                            ("VENDEDOR", "Vendedor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="hierarchy.hierarchynode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HierarchyClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("depth", models.PositiveIntegerField()),
                (
                    "ancestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closure_descendants",
                        to="hierarchy.hierarchynode",
                    ),
                ),
                (
                    "descendant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closure_ancestors",
                        to="hierarchy.hierarchynode",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="hierarchynode",
            index=models.Index(fields=["level", "ativo"], name="hierarchy_h_level_e01761_idx"),
        ),
        migrations.AddIndex(
            model_name="hierarchyclosure",
            index=models.Index(fields=["ancestor"], name="hierarchy_h_ancesto_545b3b_idx"),
        ),
        migrations.AddIndex(
            model_name="hierarchyclosure",
            index=models.Index(fields=["descendant"], name="hierarchy_h_descend_cb1259_idx"),
        ),
        migrations.AddConstraint(
            model_name="hierarchyclosure",
            constraint=models.UniqueConstraint(
                fields=("ancestor", "descendant"), name="uniq_hierarchy_closure_pair"
            ),
        ),
    ]
