# Generated by Django 5.2.16 on 2026-07-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSalespersonMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_name", models.CharField(max_length=150, unique=True)),
                (
                    "hierarchy_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_salesperson_mappings",
                        to="hierarchy.hierarchynode",
                    ),
                ),
            ],
        ),
    ]
