# Generated by Django 5.2.16 on 2026-07-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hierarchy", "0002_externalsalespersonmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeristaCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_name", models.CharField(max_length=150)),
                ("ano", models.PositiveSmallIntegerField()),
                ("mes", models.PositiveSmallIntegerField()),
                (
                    "covered_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ferista_coverages",
                        to="hierarchy.hierarchynode",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("external_name", "ano", "mes"), name="uniq_ferista_coverage_month"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("mes__gte", 1), ("mes__lte", 12)),
                        name="ferista_coverage_mes_valido",
                    ),
                ],
            },
        ),
    ]
